version: "3.9"
services:

  db:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_USER: laravel
      MARIADB_PASSWORD: root
      MARIADB_ROOT_PASSWORD: laravel
      MARIADB_DATABASE: laravel
    networks: 
      - mon_reseau

  web:
    image: nginx:alpine
    volumes:
    - ./templates:/etc/nginx/templates
    ports:
    - "8100:80"
    environment:
    - NGINX_HOST=foobar.com
    - NGINX_PORT=80

  app:
    image: docker.io/bitnami/laravel:9
    ports:
      - '8102:80'
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=laravel
      - DB_DATABASE=laravel
    volumes:
      - './my-project:/app'
    networks: 
      - mon_reseau
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST : db
      PMA_PORT : 3306
    ports:
      - 8101:80
    networks: 
      - mon_reseau

networks:
  mon_reseau:
    driver: bridge




